[simulador]
# Substitua pelo IP mostrado no output "vm_ip" do OpenTofu
vm1 ansible_host=192.168.122.228

[simulador:vars]
ansible_user=devops
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
ansible_python_interpreter=/usr/bin/python3
